### ISSUE TITLE
Need help with software

### ISSUE THREAD

**Issue by xfce** [esar/hdmilight-v2#4]
Hi  all,
Does any one still do the project, I am  now designing a single board for this, means all in one board(FPGA+HDMI splitter) , but I think I can't do the software, could someone work together with me^-^
I use ubuntu 18.04 and ise 14.7, when install the license, got bellow, could someone help me

bi4wms@bi4wms-OptiPlex-390:/opt/Xilinx/14.7/ISE_DS$ xlcm-manage
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ImportError: /opt/Xilinx/14.7/ISE_DS/ISE/lib/lin64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: /opt/Xilinx/14.7/ISE_DS/ISE/lib/lin64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so)

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ImportError: /opt/Xilinx/14.7/ISE_DS/ISE/lib/lin64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so)

**Comment by esar** [comment]
Hi, it looks like the real problem is that it can't find the xlcm-manage program. The rest of the output is from the tool that is supposed to give you some suggestions on what to do, but it seems it's broken. You can see someone with a similar issue here:
https://unix.stackexchange.com/questions/9580/why-is-this-python-error-message-generated-whenever-i-type-a-nonsense-command

You might just need to specify the full path to the command. Does it find it if you run:
locate xlcm-manage

I don't have that program on my machines, but I'm still running ISE 14.4 so it might be something new.

BTW, what chipset are you using for the splitter?

**Comment by xfce** [comment]
@esar Thanks, I will try .
For the splitter, I just find EP9132 , IT6661FN, still not deep in. and would you please give some advice?

**Comment by esar** [comment]
I'm not sure I can give much advice. I've had a small amount of experience with the EP9132 and 9142, but only just enough to be able to stop them encrypting the output. You can read about my experiences with that here:
https://hacks.esar.org.uk/hdmi-splitter-hack/

The one thing that I did learn when doing that was that getting video output is pretty easy, the harder part is handling the feature support and crypto negotiation that the companion microcontroller handles. If you aren't interested in having the output encrypted then you might just need to relay the EDID info from the output port to the input port. 

I've no idea if this will actually work, but I wonder if you could connect the DDC pins of the input port to the ADV7611 instead of the EP9132. Then detect when something is plugged into the output port, query its EDID info and write that to the EDID memory in the ADV7611 and then cycle the hotplug to made the source device re-read the EDID from the ADV7611. If that works then you may be able to avoid the companion EPF011A microcontroller and its firmware.

**Comment by xfce** [comment]
@esar OK thanks , I will fellow your V3-HDMILIGHT, so close this issue.
