### ISSUE TITLE
Write bit file to SPI FLASH error

### ISSUE THREAD

**Issue by xfce** [esar/hdmilight-v2#5]
Hi @esar ,
 My single board have done, and write the hdmilight.bit to FPGA use Papilio Loader 2.8 is OK, also test the serial cmd, everything work, but can't write file to SPI FLASH, seems same error as my V3 board. can you help me use the openocd to write bit file to SPI FLASH, as V3 board I can try many times use openocd then write the bit file to SPI FLASH, THANKS
And if you can give me another type SPI FLASH for the FPGA, maybe I can have a try, THANKS 

Bellow is the Papilio Loader's log
Using devlist.txt
JTAG chainpos: 0 Device IDCODE = 0x24001093	Desc: XC6SLX9
Using devlist.txt
JTAG chainpos: 0 Device IDCODE = 0x24001093	Desc: XC6SLX9
Trying reconfigure

Uploading "/opt/GadgetFactory/papilio-loader/programmer/bscan_spi_xc6slx9.bit". DNA is 0x59faae82210299fe
Done.
Programming time 552.0 ms

Programming External Flash Memory with "/home/bi4wms/Downloads/hdmilight-v2-master/hdmilight.bit".
Uknown Flash Manufacturer (0x01)
Error: SPI Status Register [0xFF] mismatch (Wrong device or device not ready)..
Error occured.
USB transactions: Write 178 read 9 retries 9
Using devlist.txt
JTAG chainpos: 0 Device IDCODE = 0x24001093	Desc: XC6SLX9

ISC_Done       = 0
ISC_Enabled    = 0
House Cleaning = 1
DONE           = 0

**Comment by esar** [comment]
@xfce When you say that the serial commands work, do you mean the HDMI Light commands, like ? showing the help? If that works then the write to the FPGA flash must have worked as in this version the CPU is implemented in the FPGA and the firmware is stored in the FPGA flash

There will be a problem with using openocd with the v2 project at the moment. There is currently no tool that can append config.bin to the binary .bin file that openocd can write. Currently the tools only know how to append it to the .bit version of the file. Making it work would require doing the folowing:
1) Copy hdmilight-v3-openocd.cfg from the v3 project and remove this line: source [find target/stm32f3x.cfg]
2) In Xilinx ISE change the project settings to also generate a .bin file as well as the .bit
3) Update the DATA2MEM command to merge the firmware into the .bin file instead of the .bit file... modify this command in the Makefile:
$(DATA2MEM) -bm fpga/progmem_bd.bmm -bt fpga/HdmilightTop.bit -bd firmware/image.mem -o b hdmilight-preconfig.bit
4) Add support to tools/bitmerge.py to make it work with the .bin format file
5) Use the openocd command from the v3 project to write the merged .bin file: 
openocd -f hdmilight-v3-openocd.cfg -c "init; targets xc6s.proxy; jtagspi_init 0 bscan_spi_xc6slx9.bit; jtagspi_program hdmilight.bin 0; xc6s_program xc6s.tap; shutdown"

I don't know if this is actually possible, and there are probably mistakes in these instructions, but that is roughly what needs to be done

**Comment by xfce** [comment]
Hi @esar ,
   Yes, all serial commands are OK, and I have test them fellow your V3's wiki.
   I have  used  the openocd -f hdmilight-v3-openocd.cfg ...  command ,and can finish to write the SPI flash, just used the V3's bit file for the test.
But I can't get the right hdmilight.bin file for V2, so for your step3 and step4 above, could you please help me, give the complete command, thanks a lot

**Comment by esar** [comment]
@xfce If the serial commands are working ok then the PapilioLoader must have successfully written the bit file to the FPGA flash. Is the problem just that you can't write it a second time?
If that is the case then you could try holding the FPGA reset, then starting the loader, and then quickly releasing the reset. This might help if the running design is interfering with writing.

Regarding using openocd, you will either need to update the tools to generate a .bin file instead of a .bit file, or leave the tools working with the .bit file as they do now and then find a way to convert the .bit file to a .bin file. 
The .bin file is just the raw data that needs to be written to the flash. The .bit file is sort of the same but it has some extra headers on the beginning that need removing.
I don't know the commands that are needed to do this, and I don't have time to work out how to do it at the moment.

**Comment by xfce** [comment]
Hi @esar 
Flash Seems OK now, 
but some problem,
most serial command response OK, but the LED strip can't work, just the first one lit up green.
the  GF response is different from hdmilightV3, and others sees the same.
\> GF                                                                               
raw: 0 0 0 0 0 0                                                                   
fmt: -1x-1 1.77 (0)   

But for V3  got bellow
\> GF                                                                               
raw: 1916 0 4 1080 0 0                                                             
fmt: 1916x1080 1.77 (0)

I think it's the config data lost, but i have no idea what to next,

**Comment by esar** [comment]
@xfce From that GF command it looks like the FPGA is not receiving a video signal from the ADV7611.

Do you have all of the pins between the ADV7611 and the FPGA connected to the same FPGA pins as on the original v2 design? Or did you change some to make routing easier?

If you run these two commands to read the version number from the ADV7611, do you get 0x20 and 0x51 as the result?:
GI 0x98 0xea
GI 0x98 0xeb

Can you run the "R" command? What output does it give?
It should output a long list of register addresses, each followed by either ACK or NACK
Does the GF output change after running R?

If there is still no change then can you check the LLC, VS, HS and DE signals from the ADV7611 with an oscilloscope and see if there is any activity?
LLC is the main video clock, depending on the mode it will be up to about 166MHz
VS and HS are the horizontal and vertical sync pulses, there should be one HS pulse per line of video, and one VS pulse per frame.
DE is data enable and marks which parts of each line contain valid pixel data. It should pulse at a similar rate to the HS signal.

**Comment by xfce** [comment]
I just fellow the original V2 design, I will double check the schematic and the pcb wire next step,

Now, some serial command as bellow
\> GF                                                                                 
raw: 0 0 0 0 0 0                                                                     
fmt: -1x-1 1.77 (0)                                                                  
                                                                                     
\> GI 0x98 0xea                                                                       
Read: 32 (0x20)                                                                      
                                                                                     
\> GI 0x98 0xeb                                                                       
Read: 81 (0x51)                                                                      
                                                                                     
\> R                                                                                  
152 244 128 : NACK NACK
                                                              
\> GF                                                                                 
raw: 0 0 0 0 0 0                                                                     
fmt: -1x-1 1.77 (0) 
                                                                 
\> 
And one more thing, when I remove the HDMI connection
minicom output bellow for ever, the connect HDMI, it stop
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                              
CEC 16: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff

**Comment by xfce** [comment]
Hi @esar ,

\> GF                                                                                 
raw: 636 0 4 480 0 0                                                                 
fmt: 636x480 1.77 (0)                                                                
                                                                                     
\> R                                                                                  
152 244 128 : NACK NACK                                                              
\> GF                                                                                 
raw: 636 0 4 480 0 0                                                                 
fmt: 636x480 1.77 (0)

**Comment by esar** [comment]
@xfce Cool, looks like you've now got 640x480 video coming out of the ADV7611, I'm guessing that's the default blue screen that's shown when there is no video source connected. Which pins had moved?

**Comment by xfce** [comment]
Hi @esar ,
When  power up leds all off, after  type 
\> R
I can get 20 LEDS lit blue, but then noting, also did not change corlor with HDMI signal.

**Comment by esar** [comment]
@xfce The GPIO pins are just spare pins that can be used for future expansion. They are mapped to PORTD in the AVR microcontroller. 

When you connect a video source, does the GF command give different output? Or does it always give the same 636x480?
Does the LED by the HDMI port light when the video source is connected?
What resolution is the video source?

**Comment by xfce** [comment]
@esar When HDMI source connect, GF still give the same output, always same 636\*480.
And  also LEDs still off , only I type “R” then the first 20 LEDs turn blue, video source is 1920*1080, cause HDMIlightV3 all  OK.

**Comment by esar** [comment]
@xfce You don't need to change anything else for the changed pins. That problem is now fixed as you now get 640x480 video from the ADV7611 instead of 0x0. That 640x480 video signal is being generated internally in the ADV7611. It is the blue screen that is displays when there is not a video source.

Because you only get the blue LEDs when you run the R command, the firmware must not be initialising automatically. There is a #define in main.c that should be enabled by default, but it looks like that isn't working. For now you will need to always run R, we can work out what that problem is after we get incoming video working.

The main problem now seems to be that the ADV7611 doesn't think there is a video source. Maybe there are some bad connections between the HDMI connector, the ESD chip, and the ADV7611.

Because the LED doesn't light that tells us that the ADV7611 is not asserting HPA. This signal is used to tell the video source that something is connected and that it can read the EDID to find the supported resolutions and then send video. The ADV7611 should assert this signal when the EDID RAM has been written (happens when you run R) and when it detects a cable plugged in.

The first thing that I would check is if there is 5V on pin 64 of the ADV7611. This 5V comes from the HDMI cable and tells the ADV7611 that a cable is connected. If this is present then next check HPA_A on pin 1 of the ADV7611 to see if it is high, then follow the signal through the ESD chip and the transistor pair

**Comment by xfce** [comment]
Hi @esar , 
As fellowed with your clues, found the HPA_A signal was strange, and finaly I resolder a new ADV7611, then power up with no HDMI signal, type GF, give 640*480, plugin HDMI signal, type GF again,give 1920*1080, seems everything worked, Thanks a lot.
